# distance bounds
min_distance: 0.010
max_distance: 300
# point count thresholds for all the sectors and qualities
required_points:
  short:
    min: 5
    reliable: 10
  mid:
    min: 5
    reliable: 10
  long:
    min: 3
    reliable: 7